=== marcosfergar/Lenguaje_de_Marcas/104PORYECTODAW-main/104LMSGIProyectoLMSGI/ud4/01/01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Declaracion de elementos simples -->
<xs:simpleType name="tipoRemitente">
    <xs:restriction base="xs:string"/>
</xs:simpleType>
<xs:simpleType name="tipoasunto">
    <xs:restriction base="xs:string"/>
</xs:simpleType>
<xs:simpleType name="tipoStrong">
    <xs:restriction base="xs:string"/>
</xs:simpleType>
<xs:simpleType name="tipoDia">
    <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="31"/>
    </xs:restriction>       
</xs:simpleType>
<xs:simpleType name="tipoMes">
    <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="12"/>
    </xs:restriction>       
</xs:simpleType>
<!-- Declaracion de elementos complejos -->
<xs:complexType name="tipodestinatarios">
    <xs:sequence>
        <xs:element name="destinatario" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipofechamensaje">
    <xs:sequence>
        <xs:element name="dia" type="tipoDia"/>
        <xs:element name="mes" type="tipoMes"/>
        <xs:element name="anio" type="xs:gYear"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipomensaje">
    <xs:choice maxOccurs="unbounded">
        <xs:element name="p" type="tipoP"/>
        <xs:element name="strong" type="tipoStrong"/>
        <xs:element name="h2" type="tipoH2"/>
        <xs:element name="h3" type="tipoH3"/>
        <xs:element name="ul" type="tipoUl"/>
        <xs:element name="li" type="tipoLi"/>
    </xs:choice>
</xs:complexType>
<xs:complexType name="tipoP" mixed="true">
    <xs:sequence>
        <xs:element name="strong" type="tipoStrong" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipoH2" mixed="true">
    <xs:sequence>
        <xs:element name="strong" type="tipoStrong" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipoH3" mixed="true">
    <xs:sequence>
        <xs:element name="strong" type="tipoStrong" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipoUl" mixed="true">
    <xs:sequence>
        <xs:element name="strong" type="tipoStrong" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="li" type="tipoLi" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipoLi" mixed="true">
    <xs:sequence>
        <xs:element name="strong" type="tipoStrong" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipoficheros_adjuntos">
    <xs:sequence>
        <xs:element name="fichero" type="tipoFichero" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="tipoFichero">
    <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="tipo" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
<!-- Declaracion de grupos de atributos-->
<!-- Declaracion del esquema -->
    <xs:element name="mail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="remitente" type="tipoRemitente" />
                <xs:element name="destinatarios" type="tipodestinatarios" />
                <xs:element name="fechamensaje" type="tipofechamensaje" />
                <xs:element name="asunto" type="tipoasunto" minOccurs="0"/>
                <xs:element name="mensaje" type="tipomensaje" />
                <xs:element name="ficheros_adjuntos" type="tipoficheros_adjuntos" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcosfergar/Lenguaje_de_Marcas/104PORYECTODAW-main/104LMSGIProyectoLMSGI/ud4/01/01.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mail [
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT fichero (nombre, tipo)>
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatarios (destinatario+)>
    <!ELEMENT fechamensaje (dia, mes, anio)>
    <!ELEMENT strong (#PCDATA)>
    <!ELEMENT p (#PCDATA|strong)*>
    <!ELEMENT h2 (#PCDATA|strong)*>
    <!ELEMENT h3 (#PCDATA|strong)*>
    <!ELEMENT ul (#PCDATA|strong|li)*>
    <!ELEMENT li (#PCDATA|strong)*>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA|p|strong|h2|h3|ul|li)*>
    <!ELEMENT ficheros_adjuntos (fichero+)>
    <!ELEMENT mail (remitente,destinatarios,fechamensaje,asunto?,mensaje,ficheros_adjuntos?)>
    <!ATTLIST mail 
    xmlns:xsi CDATA #IMPLIED 
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED 
    >
]>
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>pepe@gmail.com</remitente>
    <destinatarios>
        <destinatario>maria@gmail.com</destinatario>
        <destinatario>sofia@gmail.com</destinatario>
    </destinatarios>
    <fechamensaje>
        <dia>25</dia>
        <mes>11</mes>
        <anio>2024</anio>
    </fechamensaje>
    <asunto>Cena Navidad 2024</asunto>
    <mensaje>
        <p>Invitación a la Cena de Navidad</p>
        <p>Querido/a <strong>compañero/a</strong>:</p>
        <p>Nos complace invitarle a compartir una noche especial en 
        nuestra <strong></strong>Cena de Navidad, que se celebrará en el 
        encantador <strong></strong>Parador de Benavente.</p>
        <h2><strong>Detalles del Evento:</strong></h2>
        <ul>
            <li><strong>Fecha:</strong> Jueves, 21 de diciembre de 2023</li>
            <li><strong>Hora:</strong> 21:00</li>
            <li><strong>Lugar:</strong> Parador de Benavente</li>
        </ul>  
        <p>Ven a disfrutar de una velada inolvidable llena de buena compañía, 
        deliciosa gastronomía y el espíritu navideño que tanto nos une. Habremos 
        preparado un menú especial pensado para celebrar este mágica ocasión.</p>
        <p><strong>Por favor, confirma tu asistencia antes del 15 de 
        diciembre de 2023</strong> respondiendo a este correo o 
        contactando al <strong>[teléfono/email de contacto]</strong></p>
        <p>Esperamos conytar contigo para hacer de esta cena un momento añun más especial. ¡No valtes!</p>
        <p>Con cariño</p>
        <p>Director</p>    
    </mensaje>
    <ficheros_adjuntos>
        <fichero>
            <nombre>documento.pdf</nombre>
            <tipo>application/pdf</tipo>
        </fichero>
        <fichero>
            <nombre>imagen.png</nombre>
            <tipo>image/png</tipo>
        </fichero>
    </ficheros_adjuntos>
</mail>
